[
    {
      label: 'Party',
      date: '2023-12-21T18:38:48.282Z',
      cost: 30,
      image: 'https://example.com/image.jpg',
      plases: 177,
      plasTaking: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      location: 'City, Country',
      dressCode: 'Casual',
      ArrivalInstructions: 'Arrive on time',
      AgeRestriction: '18+',
      organizerEvent: 'Event Organizer'
    },
    {
      label: 'Festival',
      date: '2023-12-24T18:38:48.282Z',
      cost: 60,
      image: 'https://example.com/image.jpg',
      plases: 809,
      plasTaking: 644,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      location: 'City, Country',
      dressCode: 'Casual',
      ArrivalInstructions: 'Arrive on time',
      AgeRestriction: '18+',
      organizerEvent: 'Event Organizer'
    },
    {
      label: 'Conference',
      date: '2023-12-13T18:38:48.282Z',
      cost: 97,
      image: 'https://example.com/image.jpg',
      plases: 432,
      plasTaking: 59,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      location: 'City, Country',
      dressCode: 'Casual',
      ArrivalInstructions: 'Arrive on time',
      AgeRestriction: '18+',
      organizerEvent: 'Event Organizer'
    },
    {
      label: 'Conference',
      date: '2023-12-17T18:38:48.282Z',
      cost: 0,
      image: 'https://example.com/image.jpg',
      plases: 966,
      plasTaking: 180,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      location: 'City, Country',
      dressCode: 'Casual',
      ArrivalInstructions: 'Arrive on time',
      AgeRestriction: '18+',
      organizerEvent: 'Event Organizer'
    },
    {
      label: 'Concert',
      date: '2023-12-09T18:38:48.282Z',
      cost: 73,
      image: 'https://example.com/image.jpg',
      plases: 784,
      plasTaking: 607,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      location: 'City, Country',
      dressCode: 'Casual',
      ArrivalInstructions: 'Arrive on time',
      AgeRestriction: '18+',
      organizerEvent: 'Event Organizer'
    }
  ]